/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rack.glb 
*/

import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

const Rack = (props) => {
  const { nodes, materials } = useGLTF('/models/rack.glb');
  const rusticTextureProps = useTexture({
    map: '/textures/rustic/Wood_027_basecolor.jpg',
    normalMap: '/textures/rustic/Wood_027_normal.jpg',
    roughnessMap: '/textures/rustic/Wood_027_roughness.jpg',
    aoMap: '/textures/rustic/Wood_027_ambientOcclusion.jpg',
    });


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.frame.geometry} material={materials.Material} position={[0, 0, -0.021]} rotation={[0, 0, Math.PI / 4]} />
      <mesh geometry={nodes.bench.geometry}  position={[-0.117, -0.118, -0.021] }>
        <meshStandardMaterial {...rusticTextureProps} aoMap={rusticTextureProps.aoMap}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/rack.glb')

export default Rack;